# ============================================================
# app/agents/report_agent.py
# ============================================================
# Report Agent — Phase 2 (Sequential, Step 3)
#
# Generates the final structured Markdown research report
# using the approved summary and fact-check results.
#
# This agent only runs AFTER the doctor approves via HITL.
#
# Flow:
#   1. Read summary, fact_check_results, sources from state
#   2. Format everything into a structured prompt
#   3. Generate final Markdown report using LLM
#   4. Write final_report back to state
# ============================================================

from typing import List, Dict, Any

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage

from app.utils.config import config
from app.utils.prompts import REPORT_AGENT_PROMPT
from app.graph.state import ResearchState


# ── LLM Setup ─────────────────────────────────────────────────
llm = ChatGroq(
    api_key=config.GROQ_API_KEY,
    model=config.GROQ_MODEL,
    temperature=config.GROQ_TEMPERATURE,
    max_tokens=config.GROQ_MAX_TOKENS
)

def format_fact_check_results(results: List[Dict[str, Any]]) -> str:
    """
    Format fact-check results into a readable string for the prompt.

    Args:
        results: List of {claim, status, source, note} dicts.

    Returns:
        Formatted string with status emoji for each claim.
    """
    if not results:
        return "No fact-check results available."

    formatted = ""
    for i, r in enumerate(results, 1):
        # Map status to emoji for visual clarity in the report
        status_emoji = {
            "VERIFIED":     "✅",
            "UNVERIFIED":   "⚠️",
            "CONTRADICTED": "❌"
        }.get(r.get("status", ""), "❓")
        
        formatted += (
            f"\n[{i}] {status_emoji} {r.get('claim', '')}\n"
            f"     Status: {r.get('status', '')} | "
            f"Source: {r.get('source', 'N/A')}\n"
        )
        # Add note if present
        if r.get("note"):
            formatted += f"     Note: {r['note']}\n"

    return formatted

def format_sources(sources: List[str]) -> str:
    """
    Format source URLs into a numbered bibliography.

    Args:
        sources: List of source URL strings.

    Returns:
        Numbered bibliography string.
    """
    if not sources:
        return "No sources available."

    # Remove empty strings and duplicates
    clean_sources = list({s for s in sources if s})

    formatted = ""
    for i, source in enumerate(clean_sources, 1):
        formatted += f"\n[{i}] {source}"
        
    return formatted

def run_report_agent(state: ResearchState) -> ResearchState:
    """
    Main Report Agent — called by LangGraph as a node.

    Only runs after HITL approval — the workflow router
    checks hitl_decision == APPROVED before calling this.

    Reads from state:  summary, fact_check_results, sources,
                       query, focus_area, hitl_comments,
                       confidence_score
    Writes to state:   final_report

    Args:
        state: Current ResearchState from LangGraph.

    Returns:
        Updated state with final_report filled in.
    """
    print(" Report Agent running...")
    
    query = state["query"]
    focus_area = state.get("focus_area", "general")
    
    try:
        # Step 1: Format all inputs for the report prompt
        fact_check_text = format_fact_check_results(
            state.get("fact_check_results", [])
        )
        sources_text = format_sources(
            state.get("sources", [])
        )
        
        # Get doctor's comments from HITL — empty string if none
        hitl_comments = state.get("hitl_comments", "No additional comments.")
        confidence = state.get("confidence_score", 0)
        
        print("   Generating final report...")

        # Step 2: Fill in the report prompt template
        prompt = REPORT_AGENT_PROMPT.format(
            query=query,
            focus_area=focus_area,
            hitl_comments=hitl_comments,
            summary=state.get("summary", ""),
            fact_check_results=fact_check_text,
            sources=sources_text
        )

        # Step 3: Generate the final report
        response = llm.invoke([HumanMessage(content=prompt)])
        final_report = response.content
        
        # Step 4: Append confidence score and disclaimer
        # These are always appended regardless of LLM output
        final_report += f"\n\n---\n**Overall Confidence Score: {confidence}/100**"
        final_report += (
            "\n\n---\n"
            "## ⚠️ Medical Disclaimer\n"
            "This report is generated by an AI system for research "
            "and educational purposes only. It does not constitute "
            "medical advice. Always consult a qualified medical "
            "professional for clinical decisions."
        )
        
        print(f"✅ Report generated ({len(final_report)} characters)")

        return {
            **state,
            "final_report": final_report
        }

    except Exception as e:
        print(f"❌ Report Agent failed: {e}")
        return {
            **state,
            "final_report": "",
            "error":        f"Report Agent error: {str(e)}"
        }